#!/usr/bin/env node
/**
 * render-nodes.mjs
 * ----------------------------------------------------------------------------
 * Renders .claude/project-map/project-map.json into docs/nodes.md.
 *
 * nodes.md is a VIEW, never the source of truth. It exists so a human (and
 * Claude) can see module boundaries and dependencies at a glance, and so Claude
 * can route a task to the right node(s) before opening any file.
 *
 * Hard rule baked into the header: the map tells you WHICH files to read; you
 * still READ those files before editing. Never edit against the map alone.
 */

import { existsSync, readFileSync, mkdirSync, writeFileSync } from "node:fs";
import { join, dirname } from "node:path";

const ROOT = process.cwd();
const IN_JSON = join(ROOT, ".claude", "project-map", "project-map.json");
const OUT_MD = join(ROOT, "docs", "nodes.md");

if (!existsSync(IN_JSON)) {
  console.error("[cartographer] project-map.json not found. Run build-map.mjs first.");
  process.exit(1);
}

const map = JSON.parse(readFileSync(IN_JSON, "utf8"));

const LAYER_ORDER = ["ui", "api", "domain", "data", "lib", "config", "module"];
function safeId(id) {
  return "n_" + id.replace(/[^a-zA-Z0-9]/g, "_");
}

// group nodes by layer for Mermaid subgraphs
const byLayer = new Map();
for (const n of map.nodes) {
  if (!byLayer.has(n.layer)) byLayer.set(n.layer, []);
  byLayer.get(n.layer).push(n);
}

let mermaid = "```mermaid\ngraph LR\n";
for (const layer of LAYER_ORDER) {
  const group = byLayer.get(layer);
  if (!group?.length) continue;
  mermaid += `  subgraph ${layer.toUpperCase()}\n`;
  for (const n of group) {
    mermaid += `    ${safeId(n.id)}["${n.id}<br/>(${n.fileCount} ${n.fileCount === 1 ? "file" : "files"})"]\n`;
  }
  mermaid += "  end\n";
}
for (const e of map.edges) {
  mermaid += `  ${safeId(e.from)} --> ${safeId(e.to)}\n`;
}
mermaid += "```\n";

// node reference table
let table = "| Node | Layer | Files | Entry points | Depends on |\n";
table += "|---|---|---:|---|---|\n";
for (const n of map.nodes) {
  const entries = n.entrypoints.length ? n.entrypoints.map((f) => `\`${f}\``).join("<br/>") : "—";
  const deps = n.dependsOn.length ? n.dependsOn.map((d) => `\`${d}\``).join(", ") : "—";
  table += `| \`${n.id}\` | ${n.layer} | ${n.fileCount} | ${entries} | ${deps} |\n`;
}

const md = `# Project Node Map

> **Generated by project-cartographer — do not edit by hand.**
> Source of truth: \`.claude/project-map/project-map.json\`. Regenerate with \`/cartographer:map\`.
> Last generated: ${map.generatedAt} · content hash: \`${map.contentHash}\`

## How to use this map

1. This map is a **router**, not a source of truth for code. Use it to decide
   **which node(s)** a task touches.
2. Then **open and read the actual files** in those nodes before editing. The
   map can lag behind the code; the files cannot.
3. If the code's real structure disagrees with this map, the map is stale —
   regenerate it (\`/cartographer:map\`) and trust the files.

## Dependency graph

${mermaid}

## Node reference

${table}
`;

mkdirSync(dirname(OUT_MD), { recursive: true });
writeFileSync(OUT_MD, md, "utf8");
console.error(`[cartographer] wrote ${OUT_MD}`);
